---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: remove nginx
    apt:
      name: nginx
      state: absent  

    when: ansible_distribution == "Ubuntu" 
