---

- hosts: all
  become: true
  pre_tasks:

  - name: Install_updates(CentOS)
    dnf:
      update_only: yes
      update_cache: yes 
    when: ansible_version == "CentOS"


  - name: Install_updates(Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes 
    when: ansible_version == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: Install user laroid
    user: 
      name: laroid
      groups: root
    when: ansible_distribution == "Ubuntu" 

- hosts: web_servers
  become: true
  tasks:

  - name: install nginx
    apt:
      name: nginx
      state: latest
    when: ansible_distribution == "Ubuntu" 

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb on CentOS
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS" 

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb on Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba
    package:
      name: samba
      state: latest
